server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://application-spring-cloud-eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: true
  instance:
    prefer-ip-address: true