apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "80"
  EUREKA_SERVICE_ENDPOINT: http://application-spring-cloud-eureka
  CONFIG_SERVICE_ENDPOINT: http://spring-cloud-config-service